### ISSUE TITLE
wasmtime demo command fail to execute markdown.wasm

### ISSUE THREAD

**Issue by whalelephant** [bytecodealliance/wasmtime-demos#16] opened 2020-01-17 05:26 UTC
Following the demo in this [youtube video](https://www.youtube.com/watch?time_continue=198&v=Qn_4F3foB3Q&feature=emb_logo) with a clone of this directory, I was unable to use wasmtime to run `wasmtime markdown.wasm --invoke render "# Hello" `  

**wasmtime version 0.9.0**

Error:
```
~/wasmtime-demos/markdown(master) » wasmtime markdown.wasm --invoke render "# Hello" 
Error: failed to run main module `markdown.wasm`

Caused by:
    func type returns multiple values (at offset 47)
```

**Comment by tomasol** [comment] 2020-01-30 22:43
Seems to be duplicate of #2

**Comment by alexcrichton** [comment] 2020-03-13 19:55
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!

**Closed as completed by alexcrichton** 2020-03-13 19:55 UTC
